/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package treba;

public class gibbs_state_chain {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected gibbs_state_chain(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(gibbs_state_chain obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trebaJNI.delete_gibbs_state_chain(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setState(int value) {
    trebaJNI.gibbs_state_chain_state_set(swigCPtr, this, value);
  }

  public int getState() {
    return trebaJNI.gibbs_state_chain_state_get(swigCPtr, this);
  }

  public void setSym(int value) {
    trebaJNI.gibbs_state_chain_sym_set(swigCPtr, this, value);
  }

  public int getSym() {
    return trebaJNI.gibbs_state_chain_sym_get(swigCPtr, this);
  }

  public gibbs_state_chain() {
    this(trebaJNI.new_gibbs_state_chain(), true);
  }

}
