/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package treba;

public class hmm {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected hmm(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(hmm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trebaJNI.delete_hmm(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNum_states(int value) {
    trebaJNI.hmm_num_states_set(swigCPtr, this, value);
  }

  public int getNum_states() {
    return trebaJNI.hmm_num_states_get(swigCPtr, this);
  }

  public void setAlphabet_size(int value) {
    trebaJNI.hmm_alphabet_size_set(swigCPtr, this, value);
  }

  public int getAlphabet_size() {
    return trebaJNI.hmm_alphabet_size_get(swigCPtr, this);
  }

  public void setTransition_table(SWIGTYPE_p_double value) {
    trebaJNI.hmm_transition_table_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getTransition_table() {
    long cPtr = trebaJNI.hmm_transition_table_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setEmission_table(SWIGTYPE_p_double value) {
    trebaJNI.hmm_emission_table_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getEmission_table() {
    long cPtr = trebaJNI.hmm_emission_table_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public hmm() {
    this(trebaJNI.new_hmm(), true);
  }

}
