/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package treba;

public class observations {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected observations(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(observations obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trebaJNI.delete_observations(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSize(int value) {
    trebaJNI.observations_size_set(swigCPtr, this, value);
  }

  public int getSize() {
    return trebaJNI.observations_size_get(swigCPtr, this);
  }

  public void setData(SWIGTYPE_p_int value) {
    trebaJNI.observations_data_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getData() {
    long cPtr = trebaJNI.observations_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setOccurrences(int value) {
    trebaJNI.observations_occurrences_set(swigCPtr, this, value);
  }

  public int getOccurrences() {
    return trebaJNI.observations_occurrences_get(swigCPtr, this);
  }

  public void setNext(observations value) {
    trebaJNI.observations_next_set(swigCPtr, this, observations.getCPtr(value), value);
  }

  public observations getNext() {
    long cPtr = trebaJNI.observations_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new observations(cPtr, false);
  }

  public observations() {
    this(trebaJNI.new_observations(), true);
  }

}
