/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


 /* Includes the header in the wrapper code */
 #include "treba.h"
 

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_treba_trebaJNI_LIKELIHOOD_1FORWARD_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_LIKELIHOOD_1BACKWARD_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_LIKELIHOOD_1VITERBI_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_DECODE_1FORWARD_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_DECODE_1BACKWARD_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_DECODE_1VITERBI_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_DECODE_1FORWARD_1PROB_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_DECODE_1BACKWARD_1PROB_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(8);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_DECODE_1VITERBI_1PROB_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(9);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_TRAIN_1BAUM_1WELCH_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(10);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_TRAIN_1DA_1BAUM_1WELCH_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(11);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_TRAIN_1VITERBI_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(12);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_TRAIN_1VITERBI_1BW_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(13);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_TRAIN_1VARIATIONAL_1BAYES_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(14);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_TRAIN_1GIBBS_1SAMPLING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(15);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_TRAIN_1MERGE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(16);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_TRAIN_1MDI_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(17);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_GENERATE_1WORDS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(18);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_MERGE_1TEST_1ALERGIA_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_MERGE_1TEST_1CHISQUARED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_MERGE_1TEST_1LR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_MERGE_1TEST_1BINOMIAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_MERGE_1TEST_1EXACT_1M_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_MERGE_1TEST_1EXACT_1B_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_GENERATE_1NONDETERMINISTIC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_GENERATE_1DETERMINISTIC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_GENERATE_1UNIFORM_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_GENERATE_1BAKIS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_SMRONE_1REAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_FORMAT_1REAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_FORMAT_1LOG10_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_FORMAT_1LOG2_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_FORMAT_1LN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_FORMAT_1NLOG10_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_FORMAT_1NLOG2_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_FORMAT_1NLN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_fsm_1counts_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PROB *arg1 = (PROB *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PROB **)&jarg1; 
  fsm_counts = arg1;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_fsm_1counts_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PROB *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PROB *)fsm_counts;
  *(PROB **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_fsm_1totalcounts_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PROB *arg1 = (PROB *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PROB **)&jarg1; 
  fsm_totalcounts = arg1;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_fsm_1totalcounts_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PROB *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PROB *)fsm_totalcounts;
  *(PROB **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_fsm_1finalcounts_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PROB *arg1 = (PROB *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PROB **)&jarg1; 
  fsm_finalcounts = arg1;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_fsm_1finalcounts_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PROB *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PROB *)fsm_finalcounts;
  *(PROB **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_fsm_1counts_1spin_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  _Bool *arg1 = (_Bool *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(_Bool **)&jarg1; 
  fsm_counts_spin = arg1;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_fsm_1counts_1spin_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  _Bool *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (_Bool *)fsm_counts_spin;
  *(_Bool **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_hmm_1counts_1trans_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PROB *arg1 = (PROB *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PROB **)&jarg1; 
  hmm_counts_trans = arg1;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_hmm_1counts_1trans_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PROB *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PROB *)hmm_counts_trans;
  *(PROB **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_hmm_1counts_1emit_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PROB *arg1 = (PROB *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PROB **)&jarg1; 
  hmm_counts_emit = arg1;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_hmm_1counts_1emit_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PROB *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PROB *)hmm_counts_emit;
  *(PROB **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_hmm_1totalcounts_1trans_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PROB *arg1 = (PROB *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PROB **)&jarg1; 
  hmm_totalcounts_trans = arg1;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_hmm_1totalcounts_1trans_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PROB *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PROB *)hmm_totalcounts_trans;
  *(PROB **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_hmm_1totalcounts_1emit_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PROB *arg1 = (PROB *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PROB **)&jarg1; 
  hmm_totalcounts_emit = arg1;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_hmm_1totalcounts_1emit_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PROB *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PROB *)hmm_totalcounts_emit;
  *(PROB **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_hmm_1counts_1spin_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  _Bool *arg1 = (_Bool *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(_Bool **)&jarg1; 
  hmm_counts_spin = arg1;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_hmm_1counts_1spin_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  _Bool *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (_Bool *)hmm_counts_spin;
  *(_Bool **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_thread_1args_1trellis_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct thread_args *arg1 = (struct thread_args *) 0 ;
  struct trellis *arg2 = (struct trellis *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct thread_args **)&jarg1; 
  arg2 = *(struct trellis **)&jarg2; 
  if (arg1) (arg1)->trellis = arg2;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_thread_1args_1trellis_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct thread_args *arg1 = (struct thread_args *) 0 ;
  struct trellis *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct thread_args **)&jarg1; 
  result = (struct trellis *) ((arg1)->trellis);
  *(struct trellis **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_thread_1args_1obsarray_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct thread_args *arg1 = (struct thread_args *) 0 ;
  struct observations **arg2 = (struct observations **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct thread_args **)&jarg1; 
  arg2 = *(struct observations ***)&jarg2; 
  if (arg1) (arg1)->obsarray = arg2;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_thread_1args_1obsarray_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct thread_args *arg1 = (struct thread_args *) 0 ;
  struct observations **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct thread_args **)&jarg1; 
  result = (struct observations **) ((arg1)->obsarray);
  *(struct observations ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_thread_1args_1minobs_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct thread_args *arg1 = (struct thread_args *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct thread_args **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->minobs = arg2;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_thread_1args_1minobs_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct thread_args *arg1 = (struct thread_args *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct thread_args **)&jarg1; 
  result = (int) ((arg1)->minobs);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_thread_1args_1maxobs_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct thread_args *arg1 = (struct thread_args *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct thread_args **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->maxobs = arg2;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_thread_1args_1maxobs_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct thread_args *arg1 = (struct thread_args *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct thread_args **)&jarg1; 
  result = (int) ((arg1)->maxobs);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_thread_1args_1fsmhmm_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct thread_args *arg1 = (struct thread_args *) 0 ;
  void *arg2 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct thread_args **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  if (arg1) (arg1)->fsmhmm = arg2;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_thread_1args_1fsmhmm_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct thread_args *arg1 = (struct thread_args *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct thread_args **)&jarg1; 
  result = (void *) ((arg1)->fsmhmm);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_thread_1args_1beta_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct thread_args *arg1 = (struct thread_args *) 0 ;
  PROB arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct thread_args **)&jarg1; 
  arg2 = (PROB)jarg2; 
  if (arg1) (arg1)->beta = arg2;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_thread_1args_1beta_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct thread_args *arg1 = (struct thread_args *) 0 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct thread_args **)&jarg1; 
  result = (PROB) ((arg1)->beta);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_new_1thread_1args(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct thread_args *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct thread_args *)calloc(1, sizeof(struct thread_args));
  *(struct thread_args **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_delete_1thread_1args(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct thread_args *arg1 = (struct thread_args *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct thread_args **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_g_1obsarray_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct observations *arg1 = (struct observations *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  g_obsarray = arg1;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_g_1obsarray_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct observations *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct observations *)g_obsarray;
  *(struct observations **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_wfsa_1num_1states_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->num_states = arg2;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_wfsa_1num_1states_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  result = (int) ((arg1)->num_states);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_wfsa_1alphabet_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->alphabet_size = arg2;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_wfsa_1alphabet_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  result = (int) ((arg1)->alphabet_size);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_wfsa_1state_1table_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  PROB *arg2 = (PROB *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = *(PROB **)&jarg2; 
  if (arg1) (arg1)->state_table = arg2;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_wfsa_1state_1table_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  PROB *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  result = (PROB *) ((arg1)->state_table);
  *(PROB **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_wfsa_1final_1table_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  PROB *arg2 = (PROB *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = *(PROB **)&jarg2; 
  if (arg1) (arg1)->final_table = arg2;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_wfsa_1final_1table_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  PROB *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  result = (PROB *) ((arg1)->final_table);
  *(PROB **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_new_1wfsa(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct wfsa *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct wfsa *)calloc(1, sizeof(struct wfsa));
  *(struct wfsa **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_delete_1wfsa(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct wfsa **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_hmm_1num_1states_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct hmm *arg1 = (struct hmm *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct hmm **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->num_states = arg2;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_hmm_1num_1states_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct hmm *arg1 = (struct hmm *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct hmm **)&jarg1; 
  result = (int) ((arg1)->num_states);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_hmm_1alphabet_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct hmm *arg1 = (struct hmm *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct hmm **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->alphabet_size = arg2;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_hmm_1alphabet_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct hmm *arg1 = (struct hmm *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct hmm **)&jarg1; 
  result = (int) ((arg1)->alphabet_size);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_hmm_1transition_1table_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct hmm *arg1 = (struct hmm *) 0 ;
  PROB *arg2 = (PROB *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct hmm **)&jarg1; 
  arg2 = *(PROB **)&jarg2; 
  if (arg1) (arg1)->transition_table = arg2;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_hmm_1transition_1table_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct hmm *arg1 = (struct hmm *) 0 ;
  PROB *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct hmm **)&jarg1; 
  result = (PROB *) ((arg1)->transition_table);
  *(PROB **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_hmm_1emission_1table_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct hmm *arg1 = (struct hmm *) 0 ;
  PROB *arg2 = (PROB *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct hmm **)&jarg1; 
  arg2 = *(PROB **)&jarg2; 
  if (arg1) (arg1)->emission_table = arg2;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_hmm_1emission_1table_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct hmm *arg1 = (struct hmm *) 0 ;
  PROB *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct hmm **)&jarg1; 
  result = (PROB *) ((arg1)->emission_table);
  *(PROB **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_new_1hmm(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct hmm *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct hmm *)calloc(1, sizeof(struct hmm));
  *(struct hmm **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_delete_1hmm(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct hmm *arg1 = (struct hmm *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct hmm **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_observations_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct observations *arg1 = (struct observations *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_observations_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct observations *arg1 = (struct observations *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  result = (int) ((arg1)->size);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_observations_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct observations *arg1 = (struct observations *) 0 ;
  int *arg2 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  arg2 = *(int **)&jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_observations_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct observations *arg1 = (struct observations *) 0 ;
  int *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  result = (int *) ((arg1)->data);
  *(int **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_observations_1occurrences_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct observations *arg1 = (struct observations *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->occurrences = arg2;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_observations_1occurrences_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct observations *arg1 = (struct observations *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  result = (int) ((arg1)->occurrences);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_observations_1next_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  struct observations *arg1 = (struct observations *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct observations **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  if (arg1) (arg1)->next = arg2;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_observations_1next_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct observations *arg1 = (struct observations *) 0 ;
  struct observations *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  result = (struct observations *) ((arg1)->next);
  *(struct observations **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_new_1observations(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct observations *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct observations *)calloc(1, sizeof(struct observations));
  *(struct observations **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_delete_1observations(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct observations *arg1 = (struct observations *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct observations **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_trellis_1fp_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct trellis *arg1 = (struct trellis *) 0 ;
  PROB arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct trellis **)&jarg1; 
  arg2 = (PROB)jarg2; 
  if (arg1) (arg1)->fp = arg2;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_trellis_1fp_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct trellis *arg1 = (struct trellis *) 0 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct trellis **)&jarg1; 
  result = (PROB) ((arg1)->fp);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_trellis_1bp_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct trellis *arg1 = (struct trellis *) 0 ;
  PROB arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct trellis **)&jarg1; 
  arg2 = (PROB)jarg2; 
  if (arg1) (arg1)->bp = arg2;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_trellis_1bp_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct trellis *arg1 = (struct trellis *) 0 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct trellis **)&jarg1; 
  result = (PROB) ((arg1)->bp);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_trellis_1backstate_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct trellis *arg1 = (struct trellis *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct trellis **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->backstate = arg2;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_trellis_1backstate_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct trellis *arg1 = (struct trellis *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct trellis **)&jarg1; 
  result = (int) ((arg1)->backstate);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_new_1trellis(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct trellis *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct trellis *)calloc(1, sizeof(struct trellis));
  *(struct trellis **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_delete_1trellis(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct trellis *arg1 = (struct trellis *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct trellis **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_output_1convert(JNIEnv *jenv, jclass jcls, jdouble jarg1) {
  jdouble jresult = 0 ;
  PROB arg1 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (PROB)jarg1; 
  result = (PROB)output_convert(arg1);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_input_1convert(JNIEnv *jenv, jclass jcls, jdouble jarg1) {
  jdouble jresult = 0 ;
  PROB arg1 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (PROB)jarg1; 
  result = (PROB)input_convert(arg1);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_treba_trebaJNI_file_1to_1mem(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jstring jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (char *)file_to_mem(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_char_1in_1array(JNIEnv *jenv, jclass jcls, jchar jarg1, jstring jarg2) {
  jint jresult = 0 ;
  char arg1 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (char)jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)char_in_array(arg1,arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_line_1count_1elements(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  char **arg1 = (char **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(char ***)&jarg1; 
  result = (int)line_count_elements(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_treba_trebaJNI_line_1to_1int_1array(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jlong jarg3) {
  jstring jresult = 0 ;
  char *arg1 = (char *) 0 ;
  int **arg2 = (int **) 0 ;
  int *arg3 = (int *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(int ***)&jarg2; 
  arg3 = *(int **)&jarg3; 
  result = (char *)line_to_int_array(arg1,arg2,arg3);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_hmm_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct hmm *arg1 = (struct hmm *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct hmm **)&jarg1; 
  hmm_print(arg1);
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_hmm_1init(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  struct hmm *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (struct hmm *)hmm_init(arg1,arg2);
  *(struct hmm **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_hmm_1destroy(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct hmm *arg1 = (struct hmm *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct hmm **)&jarg1; 
  hmm_destroy(arg1);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_hmm_1randomize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  struct hmm *arg1 = (struct hmm *) 0 ;
  int arg2 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct hmm **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  hmm_randomize(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_hmm_1to_1log2(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct hmm *arg1 = (struct hmm *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct hmm **)&jarg1; 
  hmm_to_log2(arg1);
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_hmm_1read_1file(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  struct hmm *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (struct hmm *)hmm_read_file(arg1);
  *(struct hmm **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_train_1viterbi_1bw_1hmm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jdouble jresult = 0 ;
  struct hmm *arg1 = (struct hmm *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct hmm **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  result = (PROB)train_viterbi_bw_hmm(arg1,arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_train_1viterbi_1hmm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3, jdouble jarg4) {
  jdouble jresult = 0 ;
  struct hmm *arg1 = (struct hmm *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  int arg3 ;
  PROB arg4 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct hmm **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (PROB)jarg4; 
  result = (PROB)train_viterbi_hmm(arg1,arg2,arg3,arg4);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_viterbi_1hmm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  struct hmm *arg1 = (struct hmm *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct hmm **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  arg3 = (int)jarg3; 
  viterbi_hmm(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_generate_1words_1hmm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct hmm *arg1 = (struct hmm *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct hmm **)&jarg1; 
  arg2 = (int)jarg2; 
  generate_words_hmm(arg1,arg2);
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_train_1bw_1hmm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3, jdouble jarg4) {
  jdouble jresult = 0 ;
  struct hmm *arg1 = (struct hmm *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  int arg3 ;
  PROB arg4 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct hmm **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (PROB)jarg4; 
  result = (PROB)train_bw_hmm(arg1,arg2,arg3,arg4);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_gibbs_1state_1chain_1state_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct gibbs_state_chain *arg1 = (struct gibbs_state_chain *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gibbs_state_chain **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->state = arg2;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_gibbs_1state_1chain_1state_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct gibbs_state_chain *arg1 = (struct gibbs_state_chain *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gibbs_state_chain **)&jarg1; 
  result = (int) ((arg1)->state);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_gibbs_1state_1chain_1sym_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct gibbs_state_chain *arg1 = (struct gibbs_state_chain *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gibbs_state_chain **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->sym = arg2;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_gibbs_1state_1chain_1sym_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct gibbs_state_chain *arg1 = (struct gibbs_state_chain *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct gibbs_state_chain **)&jarg1; 
  result = (int) ((arg1)->sym);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_new_1gibbs_1state_1chain(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct gibbs_state_chain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct gibbs_state_chain *)calloc(1, sizeof(struct gibbs_state_chain));
  *(struct gibbs_state_chain **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_delete_1gibbs_1state_1chain(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct gibbs_state_chain *arg1 = (struct gibbs_state_chain *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct gibbs_state_chain **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_gibbs_1sampler_1fsm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jdouble jarg3, jint jarg4, jint jarg5, jint jarg6, jint jarg7) {
  jdouble jresult = 0 ;
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  double arg3 ;
  int arg4 ;
  int arg5 ;
  int arg6 ;
  int arg7 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  arg3 = (double)jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (int)jarg5; 
  arg6 = (int)jarg6; 
  arg7 = (int)jarg7; 
  result = (PROB)gibbs_sampler_fsm(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_gibbs_1sampler_1hmm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jdouble jarg3, jdouble jarg4, jint jarg5, jint jarg6, jint jarg7, jint jarg8) {
  jdouble jresult = 0 ;
  struct hmm *arg1 = (struct hmm *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  double arg3 ;
  double arg4 ;
  int arg5 ;
  int arg6 ;
  int arg7 ;
  int arg8 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct hmm **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  arg3 = (double)jarg3; 
  arg4 = (double)jarg4; 
  arg5 = (int)jarg5; 
  arg6 = (int)jarg6; 
  arg7 = (int)jarg7; 
  arg8 = (int)jarg8; 
  result = (PROB)gibbs_sampler_hmm(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_gibbs_1counts_1to_1hmm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4, jint jarg5, jint jarg6, jdouble jarg7, jdouble jarg8) {
  jlong jresult = 0 ;
  struct hmm *arg1 = (struct hmm *) 0 ;
  unsigned int *arg2 = (unsigned int *) 0 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  unsigned int *arg4 = (unsigned int *) 0 ;
  int arg5 ;
  int arg6 ;
  double arg7 ;
  double arg8 ;
  struct hmm *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct hmm **)&jarg1; 
  arg2 = *(unsigned int **)&jarg2; 
  arg3 = *(unsigned int **)&jarg3; 
  arg4 = *(unsigned int **)&jarg4; 
  arg5 = (int)jarg5; 
  arg6 = (int)jarg6; 
  arg7 = (double)jarg7; 
  arg8 = (double)jarg8; 
  result = (struct hmm *)gibbs_counts_to_hmm(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  *(struct hmm **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_gibbs_1counts_1to_1wfsa(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jint jarg4, jint jarg5, jdouble jarg6, jdouble jarg7) {
  jlong jresult = 0 ;
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  unsigned int *arg2 = (unsigned int *) 0 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  int arg4 ;
  int arg5 ;
  double arg6 ;
  double arg7 ;
  struct wfsa *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = *(unsigned int **)&jarg2; 
  arg3 = *(unsigned int **)&jarg3; 
  arg4 = (int)jarg4; 
  arg5 = (int)jarg5; 
  arg6 = (double)jarg6; 
  arg7 = (double)jarg7; 
  result = (struct wfsa *)gibbs_counts_to_wfsa(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  *(struct wfsa **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_gibbs_1init_1fsm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  struct observations *arg1 = (struct observations *) 0 ;
  int arg2 ;
  int arg3 ;
  int *arg4 = (int *) 0 ;
  struct gibbs_state_chain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(int **)&jarg4; 
  result = (struct gibbs_state_chain *)gibbs_init_fsm(arg1,arg2,arg3,arg4);
  *(struct gibbs_state_chain **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_gibbs_1init_1hmm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  struct observations *arg1 = (struct observations *) 0 ;
  int arg2 ;
  int arg3 ;
  int *arg4 = (int *) 0 ;
  struct gibbs_state_chain *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(int **)&jarg4; 
  result = (struct gibbs_state_chain *)gibbs_init_hmm(arg1,arg2,arg3,arg4);
  *(struct gibbs_state_chain **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_interrupt_1sigproc(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  interrupt_sigproc();
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_spinlock_1lock(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  _Bool *arg1 = (_Bool *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(_Bool **)&jarg1; 
  spinlock_lock(arg1);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_spinlock_1unlock(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  _Bool *arg1 = (_Bool *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(_Bool **)&jarg1; 
  spinlock_unlock(arg1);
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_rand_1double(JNIEnv *jenv, jclass jcls) {
  jdouble jresult = 0 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  result = (PROB)rand_double();
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_rand_1int_1range(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (int)rand_int_range(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_wfsa_1read_1file(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  struct wfsa *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (struct wfsa *)wfsa_read_file(arg1);
  *(struct wfsa **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_wfsa_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  wfsa_print(arg1);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_wfsa_1to_1file(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  wfsa_to_file(arg1,arg2);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_wfsa_1randomize_1deterministic(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = (int)jarg2; 
  wfsa_randomize_deterministic(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_wfsa_1randomize_1nondeterministic(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  int arg2 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  wfsa_randomize_nondeterministic(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_wfsa_1init(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  struct wfsa *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (struct wfsa *)wfsa_init(arg1,arg2);
  *(struct wfsa **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_wfsa_1copy(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  struct wfsa *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  result = (struct wfsa *)wfsa_copy(arg1);
  *(struct wfsa **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_wfsa_1destroy(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  wfsa_destroy(arg1);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_wfsa_1to_1log2(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  wfsa_to_log2(arg1);
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_wfsa_1sum_1prob(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jdouble jresult = 0 ;
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  int arg2 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (PROB)wfsa_sum_prob(arg1,arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_wfsa_1random_1transition(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  int arg2 ;
  int *arg3 = (int *) 0 ;
  PROB *arg4 = (PROB *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(int **)&jarg3; 
  arg4 = *(PROB **)&jarg4; 
  result = (int)wfsa_random_transition(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_generate_1words(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = (int)jarg2; 
  generate_words(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_obssortcmp(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  struct observations **arg1 = (struct observations **) 0 ;
  struct observations **arg2 = (struct observations **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct observations ***)&jarg1; 
  arg2 = *(struct observations ***)&jarg2; 
  result = (int)obssortcmp(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_observations_1alphabet_1size(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct observations *arg1 = (struct observations *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  result = (int)observations_alphabet_size(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_observations_1to_1array(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jlong jresult = 0 ;
  struct observations *arg1 = (struct observations *) 0 ;
  int *arg2 = (int *) 0 ;
  struct observations **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  arg2 = *(int **)&jarg2; 
  result = (struct observations **)observations_to_array(arg1,arg2);
  *(struct observations ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_observations_1uniq(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct observations *arg1 = (struct observations *) 0 ;
  struct observations *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  result = (struct observations *)observations_uniq(arg1);
  *(struct observations **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_observations_1sort(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct observations *arg1 = (struct observations *) 0 ;
  struct observations *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  result = (struct observations *)observations_sort(arg1);
  *(struct observations **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_observations_1destroy(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  struct observations *arg1 = (struct observations *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  observations_destroy(arg1);
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_observations_1read(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  struct observations *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (struct observations *)observations_read(arg1);
  *(struct observations **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_loglikelihood_1all_1observations_1fsm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jdouble jresult = 0 ;
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  result = (PROB)loglikelihood_all_observations_fsm(arg1,arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_loglikelihood_1all_1observations_1hmm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jdouble jresult = 0 ;
  struct hmm *arg1 = (struct hmm *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct hmm **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  result = (PROB)loglikelihood_all_observations_hmm(arg1,arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_trellis_1backward(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jint jarg3, jlong jarg4, jobject jarg4_) {
  jdouble jresult = 0 ;
  struct trellis *arg1 = (struct trellis *) 0 ;
  int *arg2 = (int *) 0 ;
  int arg3 ;
  struct wfsa *arg4 = (struct wfsa *) 0 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg4_;
  arg1 = *(struct trellis **)&jarg1; 
  arg2 = *(int **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(struct wfsa **)&jarg4; 
  result = (PROB)trellis_backward(arg1,arg2,arg3,arg4);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_trellis_1viterbi(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jint jarg3, jlong jarg4, jobject jarg4_) {
  jdouble jresult = 0 ;
  struct trellis *arg1 = (struct trellis *) 0 ;
  int *arg2 = (int *) 0 ;
  int arg3 ;
  struct wfsa *arg4 = (struct wfsa *) 0 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg4_;
  arg1 = *(struct trellis **)&jarg1; 
  arg2 = *(int **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(struct wfsa **)&jarg4; 
  result = (PROB)trellis_viterbi(arg1,arg2,arg3,arg4);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_trellis_1forward_1fsm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jint jarg3, jlong jarg4, jobject jarg4_) {
  jdouble jresult = 0 ;
  struct trellis *arg1 = (struct trellis *) 0 ;
  int *arg2 = (int *) 0 ;
  int arg3 ;
  struct wfsa *arg4 = (struct wfsa *) 0 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg4_;
  arg1 = *(struct trellis **)&jarg1; 
  arg2 = *(int **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(struct wfsa **)&jarg4; 
  result = (PROB)trellis_forward_fsm(arg1,arg2,arg3,arg4);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_trellis_1forward_1hmm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jint jarg3, jlong jarg4, jobject jarg4_) {
  jdouble jresult = 0 ;
  struct trellis *arg1 = (struct trellis *) 0 ;
  int *arg2 = (int *) 0 ;
  int arg3 ;
  struct hmm *arg4 = (struct hmm *) 0 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg4_;
  arg1 = *(struct trellis **)&jarg1; 
  arg2 = *(int **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = *(struct hmm **)&jarg4; 
  result = (PROB)trellis_forward_hmm(arg1,arg2,arg3,arg4);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_trellis_1init(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jlong jresult = 0 ;
  struct observations *arg1 = (struct observations *) 0 ;
  int arg2 ;
  struct trellis *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (struct trellis *)trellis_init(arg1,arg2);
  *(struct trellis **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_trellis_1print(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  struct trellis *arg1 = (struct trellis *) 0 ;
  struct wfsa *arg2 = (struct wfsa *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct trellis **)&jarg1; 
  arg2 = *(struct wfsa **)&jarg2; 
  arg3 = (int)jarg3; 
  trellis_print(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_forward_1print_1path(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  struct trellis *arg1 = (struct trellis *) 0 ;
  struct wfsa *arg2 = (struct wfsa *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct trellis **)&jarg1; 
  arg2 = *(struct wfsa **)&jarg2; 
  arg3 = (int)jarg3; 
  forward_print_path(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_backward_1print_1path(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  struct trellis *arg1 = (struct trellis *) 0 ;
  struct wfsa *arg2 = (struct wfsa *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct trellis **)&jarg1; 
  arg2 = *(struct wfsa **)&jarg2; 
  arg3 = (int)jarg3; 
  backward_print_path(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_viterbi_1print_1path(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  struct trellis *arg1 = (struct trellis *) 0 ;
  struct wfsa *arg2 = (struct wfsa *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct trellis **)&jarg1; 
  arg2 = *(struct wfsa **)&jarg2; 
  arg3 = (int)jarg3; 
  viterbi_print_path(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_viterbi(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  arg3 = (int)jarg3; 
  viterbi(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_forward_1fsm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  arg3 = (int)jarg3; 
  forward_fsm(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_forward_1fsm_1to_1file(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3, jstring jarg4) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  int arg3 ;
  char *arg4 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = 0;
  if (jarg4) {
    arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
    if (!arg4) return ;
  }
  forward_fsm_to_file(arg1,arg2,arg3,arg4);
  if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, (const char *)arg4);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_forward_1hmm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  struct hmm *arg1 = (struct hmm *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct hmm **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  arg3 = (int)jarg3; 
  forward_hmm(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_backward_1fsm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  arg3 = (int)jarg3; 
  backward_fsm(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_backward_1hmm(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3) {
  struct hmm *arg1 = (struct hmm *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct hmm **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  arg3 = (int)jarg3; 
  backward_hmm(arg1,arg2,arg3);
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_train_1viterbi(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3, jdouble jarg4) {
  jdouble jresult = 0 ;
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  int arg3 ;
  PROB arg4 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (PROB)jarg4; 
  result = (PROB)train_viterbi(arg1,arg2,arg3,arg4);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_train_1baum_1welch(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3, jdouble jarg4, jint jarg5) {
  jdouble jresult = 0 ;
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  int arg3 ;
  PROB arg4 ;
  int arg5 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (PROB)jarg4; 
  arg5 = (int)jarg5; 
  result = (PROB)train_baum_welch(arg1,arg2,arg3,arg4,arg5);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_train_1bw(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jint jarg3, jdouble jarg4) {
  jdouble jresult = 0 ;
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  int arg3 ;
  PROB arg4 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (PROB)jarg4; 
  result = (PROB)train_bw(arg1,arg2,arg3,arg4);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jdouble JNICALL Java_treba_trebaJNI_train_1viterbi_1bw(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jdouble jresult = 0 ;
  struct wfsa *arg1 = (struct wfsa *) 0 ;
  struct observations *arg2 = (struct observations *) 0 ;
  PROB result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(struct wfsa **)&jarg1; 
  arg2 = *(struct observations **)&jarg2; 
  result = (PROB)train_viterbi_bw(arg1,arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_trellis_1fill_1bw(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  void *arg1 = (void *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(void **)&jarg1; 
  result = (void *)trellis_fill_bw(arg1);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_main(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2) {
  jint jresult = 0 ;
  int arg1 ;
  char **arg2 = (char **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = *(char ***)&jarg2; 
  result = (int)main(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_dffa_1num_1states_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct dffa *arg1 = (struct dffa *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct dffa **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->num_states = arg2;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_dffa_1num_1states_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct dffa *arg1 = (struct dffa *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct dffa **)&jarg1; 
  result = (int) ((arg1)->num_states);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_dffa_1alphabet_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct dffa *arg1 = (struct dffa *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct dffa **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->alphabet_size = arg2;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_dffa_1alphabet_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct dffa *arg1 = (struct dffa *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct dffa **)&jarg1; 
  result = (int) ((arg1)->alphabet_size);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_dffa_1transitions_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct dffa *arg1 = (struct dffa *) 0 ;
  int *arg2 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct dffa **)&jarg1; 
  arg2 = *(int **)&jarg2; 
  if (arg1) (arg1)->transitions = arg2;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_dffa_1transitions_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct dffa *arg1 = (struct dffa *) 0 ;
  int *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct dffa **)&jarg1; 
  result = (int *) ((arg1)->transitions);
  *(int **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_dffa_1transition_1freqs_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct dffa *arg1 = (struct dffa *) 0 ;
  int *arg2 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct dffa **)&jarg1; 
  arg2 = *(int **)&jarg2; 
  if (arg1) (arg1)->transition_freqs = arg2;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_dffa_1transition_1freqs_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct dffa *arg1 = (struct dffa *) 0 ;
  int *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct dffa **)&jarg1; 
  result = (int *) ((arg1)->transition_freqs);
  *(int **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_dffa_1final_1freqs_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct dffa *arg1 = (struct dffa *) 0 ;
  int *arg2 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct dffa **)&jarg1; 
  arg2 = *(int **)&jarg2; 
  if (arg1) (arg1)->final_freqs = arg2;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_dffa_1final_1freqs_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct dffa *arg1 = (struct dffa *) 0 ;
  int *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct dffa **)&jarg1; 
  result = (int *) ((arg1)->final_freqs);
  *(int **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_dffa_1total_1freqs_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct dffa *arg1 = (struct dffa *) 0 ;
  int *arg2 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct dffa **)&jarg1; 
  arg2 = *(int **)&jarg2; 
  if (arg1) (arg1)->total_freqs = arg2;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_dffa_1total_1freqs_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct dffa *arg1 = (struct dffa *) 0 ;
  int *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct dffa **)&jarg1; 
  result = (int *) ((arg1)->total_freqs);
  *(int **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_new_1dffa(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct dffa *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct dffa *)calloc(1, sizeof(struct dffa));
  *(struct dffa **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_delete_1dffa(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct dffa *arg1 = (struct dffa *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct dffa **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_dffa_1to_1wfsa(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct dffa *arg1 = (struct dffa *) 0 ;
  struct wfsa *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct dffa **)&jarg1; 
  result = (struct wfsa *)dffa_to_wfsa(arg1);
  *(struct wfsa **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_dffa_1state_1merge(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2, jint jarg3, jint jarg4) {
  jlong jresult = 0 ;
  struct observations *arg1 = (struct observations *) 0 ;
  PROB arg2 ;
  int arg3 ;
  int arg4 ;
  struct dffa *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  arg2 = (PROB)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  result = (struct dffa *)dffa_state_merge(arg1,arg2,arg3,arg4);
  *(struct dffa **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_dffa_1mdi(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  jlong jresult = 0 ;
  struct observations *arg1 = (struct observations *) 0 ;
  PROB arg2 ;
  struct dffa *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  arg2 = (PROB)jarg2; 
  result = (struct dffa *)dffa_mdi(arg1,arg2);
  *(struct dffa **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_observations_1to_1dffa(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct observations *arg1 = (struct observations *) 0 ;
  struct dffa *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct observations **)&jarg1; 
  result = (struct dffa *)observations_to_dffa(arg1);
  *(struct dffa **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_treba_trebaJNI_dffa_1init(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  struct dffa *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (struct dffa *)dffa_init(arg1,arg2);
  *(struct dffa **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_treba_trebaJNI_dffa_1chi2_1test(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3, jdouble jarg4) {
  jint jresult = 0 ;
  struct dffa *arg1 = (struct dffa *) 0 ;
  int arg2 ;
  int arg3 ;
  double arg4 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct dffa **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (double)jarg4; 
  result = (int)dffa_chi2_test(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_log1plus_1taylor_1init_1wrapper(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  log1plus_taylor_init_wrapper();
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_log1plus_1init_1wrapper(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  log1plus_init_wrapper();
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_log1plus_1free_1wrapper(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  log1plus_free_wrapper();
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_setPrior(JNIEnv *jenv, jclass jcls, jdouble jarg1) {
  PROB arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (PROB)jarg1; 
  setPrior(arg1);
}


SWIGEXPORT void JNICALL Java_treba_trebaJNI_setT0(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  setT0(arg1);
}


#ifdef __cplusplus
}
#endif

