/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package treba;

public interface trebaConstants {
  public final static int LIKELIHOOD_FORWARD = trebaJNI.LIKELIHOOD_FORWARD_get();
  public final static int LIKELIHOOD_BACKWARD = trebaJNI.LIKELIHOOD_BACKWARD_get();
  public final static int LIKELIHOOD_VITERBI = trebaJNI.LIKELIHOOD_VITERBI_get();
  public final static int DECODE_FORWARD = trebaJNI.DECODE_FORWARD_get();
  public final static int DECODE_BACKWARD = trebaJNI.DECODE_BACKWARD_get();
  public final static int DECODE_VITERBI = trebaJNI.DECODE_VITERBI_get();
  public final static int DECODE_FORWARD_PROB = trebaJNI.DECODE_FORWARD_PROB_get();
  public final static int DECODE_BACKWARD_PROB = trebaJNI.DECODE_BACKWARD_PROB_get();
  public final static int DECODE_VITERBI_PROB = trebaJNI.DECODE_VITERBI_PROB_get();
  public final static int TRAIN_BAUM_WELCH = trebaJNI.TRAIN_BAUM_WELCH_get();
  public final static int TRAIN_DA_BAUM_WELCH = trebaJNI.TRAIN_DA_BAUM_WELCH_get();
  public final static int TRAIN_VITERBI = trebaJNI.TRAIN_VITERBI_get();
  public final static int TRAIN_VITERBI_BW = trebaJNI.TRAIN_VITERBI_BW_get();
  public final static int TRAIN_VARIATIONAL_BAYES = trebaJNI.TRAIN_VARIATIONAL_BAYES_get();
  public final static int TRAIN_GIBBS_SAMPLING = trebaJNI.TRAIN_GIBBS_SAMPLING_get();
  public final static int TRAIN_MERGE = trebaJNI.TRAIN_MERGE_get();
  public final static int TRAIN_MDI = trebaJNI.TRAIN_MDI_get();
  public final static int GENERATE_WORDS = trebaJNI.GENERATE_WORDS_get();
  public final static int MERGE_TEST_ALERGIA = trebaJNI.MERGE_TEST_ALERGIA_get();
  public final static int MERGE_TEST_CHISQUARED = trebaJNI.MERGE_TEST_CHISQUARED_get();
  public final static int MERGE_TEST_LR = trebaJNI.MERGE_TEST_LR_get();
  public final static int MERGE_TEST_BINOMIAL = trebaJNI.MERGE_TEST_BINOMIAL_get();
  public final static int MERGE_TEST_EXACT_M = trebaJNI.MERGE_TEST_EXACT_M_get();
  public final static int MERGE_TEST_EXACT_B = trebaJNI.MERGE_TEST_EXACT_B_get();
  public final static int GENERATE_NONDETERMINISTIC = trebaJNI.GENERATE_NONDETERMINISTIC_get();
  public final static int GENERATE_DETERMINISTIC = trebaJNI.GENERATE_DETERMINISTIC_get();
  public final static int GENERATE_UNIFORM = trebaJNI.GENERATE_UNIFORM_get();
  public final static int GENERATE_BAKIS = trebaJNI.GENERATE_BAKIS_get();
  public final static int SMRONE_REAL = trebaJNI.SMRONE_REAL_get();
  public final static int FORMAT_REAL = trebaJNI.FORMAT_REAL_get();
  public final static int FORMAT_LOG10 = trebaJNI.FORMAT_LOG10_get();
  public final static int FORMAT_LOG2 = trebaJNI.FORMAT_LOG2_get();
  public final static int FORMAT_LN = trebaJNI.FORMAT_LN_get();
  public final static int FORMAT_NLOG10 = trebaJNI.FORMAT_NLOG10_get();
  public final static int FORMAT_NLOG2 = trebaJNI.FORMAT_NLOG2_get();
  public final static int FORMAT_NLN = trebaJNI.FORMAT_NLN_get();
}
