/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package treba;

public class wfsa {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected wfsa(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(wfsa obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trebaJNI.delete_wfsa(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNum_states(int value) {
    trebaJNI.wfsa_num_states_set(swigCPtr, this, value);
  }

  public int getNum_states() {
    return trebaJNI.wfsa_num_states_get(swigCPtr, this);
  }

  public void setAlphabet_size(int value) {
    trebaJNI.wfsa_alphabet_size_set(swigCPtr, this, value);
  }

  public int getAlphabet_size() {
    return trebaJNI.wfsa_alphabet_size_get(swigCPtr, this);
  }

  public void setState_table(SWIGTYPE_p_double value) {
    trebaJNI.wfsa_state_table_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getState_table() {
    long cPtr = trebaJNI.wfsa_state_table_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setFinal_table(SWIGTYPE_p_double value) {
    trebaJNI.wfsa_final_table_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getFinal_table() {
    long cPtr = trebaJNI.wfsa_final_table_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public wfsa() {
    this(trebaJNI.new_wfsa(), true);
  }

}
