/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package treba;

public class dffa {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected dffa(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(dffa obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        trebaJNI.delete_dffa(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNum_states(int value) {
    trebaJNI.dffa_num_states_set(swigCPtr, this, value);
  }

  public int getNum_states() {
    return trebaJNI.dffa_num_states_get(swigCPtr, this);
  }

  public void setAlphabet_size(int value) {
    trebaJNI.dffa_alphabet_size_set(swigCPtr, this, value);
  }

  public int getAlphabet_size() {
    return trebaJNI.dffa_alphabet_size_get(swigCPtr, this);
  }

  public void setTransitions(SWIGTYPE_p_int value) {
    trebaJNI.dffa_transitions_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getTransitions() {
    long cPtr = trebaJNI.dffa_transitions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setTransition_freqs(SWIGTYPE_p_int value) {
    trebaJNI.dffa_transition_freqs_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getTransition_freqs() {
    long cPtr = trebaJNI.dffa_transition_freqs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setFinal_freqs(SWIGTYPE_p_int value) {
    trebaJNI.dffa_final_freqs_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getFinal_freqs() {
    long cPtr = trebaJNI.dffa_final_freqs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setTotal_freqs(SWIGTYPE_p_int value) {
    trebaJNI.dffa_total_freqs_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getTotal_freqs() {
    long cPtr = trebaJNI.dffa_total_freqs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public dffa() {
    this(trebaJNI.new_dffa(), true);
  }

}
